### PR TITLE
docs: add vue graphql guide

### LINKED ISSUE #310: Write a guide for GraphQL with Vue.js
**Write a Guide for Using GraphQL with Vue, similar to the one created for React (see [React Guide](https://tailcall.run/graphql/graphql-react-client/)).**

**Objective:** Outline the top five approaches for integrating GraphQL with Vue.

---
### Approach 1
1. Installation and Integration Steps
2. Code Snippets

... Four more approaches

## Detailed Comparison Table

Create a detailed comparison table of all five methods, including factors like:

1. Bundle Size
2. Learning Curve
3. Caching Capabilities
4. Community Support
5. Additional Features

## Error Handling

Expand on error handling strategies for each method, providing detailed examples of how to gracefully handle and display errors.

## Conclusion

---

# **Requirements for Submission:**

1. **Code Verification:** Ensure all code snippets included in the article are linked to a working GitHub repository. Utilize the Tailcall backend with GraphQL on top of [jsonplaceholderAPI](https://jsonplaceholder.typicode.com/) for examples in the article. There should be a repository containing the Tailcall GraphQL configuration and a README to start the server so readers can try it.

2. **Performance Claims:** Substantiate any performance-related statements with benchmark data. Include relevant links or appendices showcasing these benchmarks to maintain credibility.

3. **Image Usage:** Use only images that are free from copyright restrictions or for which you have the appropriate rights.

4. **Tonality Consistency:** Maintain a uniform style and tone throughout the article.

5. **Expected Words**:  1500.

---

### PR DESCRIPTION
**Pull request by varshith257**
Fixes #310 
/claim #310

### CODE REVIEW

**Comment by varshith257** [comment]
TODO: 
- [ ]  Introduction
- [ ]  Detailed Comparison Table
- [ ]  TODO: Error Handling
- [ ]  Caching Capabilities
- [ ]  Conclusion

**Comment by varshith257** [comment]
Please take a look @amitksingh1490

**Comment by amitksingh1490** [comment]
@varshith257 Please provide a working examples in a github repo which we can verify, Also there are spelling mistakes in the article moving this to draft

**Comment by varshith257** [comment]
@amitksingh1490 Are you suggesting to produce output of the examples referenced?

**Comment by amitksingh1490** [comment]
yes so that I could verify the code snippet used actually works

**Comment by varshith257** [comment]
@amitksingh1490 I have done some examples and will push to GitHub once all done Currently I have exams and will be back after it

**Comment by amitksingh1490** [comment]
Closing due to missing code samples and in favour of https://github.com/tailcallhq/tailcallhq.github.io/pull/371

**Pull request closed without merging**
