### PR TITLE
feat(docs): add GraphQL in Vue guide with 5 data fetching approaches

### LINKED ISSUE #310: Write a guide for GraphQL with Vue.js
**Write a Guide for Using GraphQL with Vue, similar to the one created for React (see [React Guide](https://tailcall.run/graphql/graphql-react-client/)).**

**Objective:** Outline the top five approaches for integrating GraphQL with Vue.

---
### Approach 1
1. Installation and Integration Steps
2. Code Snippets

... Four more approaches

## Detailed Comparison Table

Create a detailed comparison table of all five methods, including factors like:

1. Bundle Size
2. Learning Curve
3. Caching Capabilities
4. Community Support
5. Additional Features

## Error Handling

Expand on error handling strategies for each method, providing detailed examples of how to gracefully handle and display errors.

## Conclusion

---

# **Requirements for Submission:**

1. **Code Verification:** Ensure all code snippets included in the article are linked to a working GitHub repository. Utilize the Tailcall backend with GraphQL on top of [jsonplaceholderAPI](https://jsonplaceholder.typicode.com/) for examples in the article. There should be a repository containing the Tailcall GraphQL configuration and a README to start the server so readers can try it.

2. **Performance Claims:** Substantiate any performance-related statements with benchmark data. Include relevant links or appendices showcasing these benchmarks to maintain credibility.

3. **Image Usage:** Use only images that are free from copyright restrictions or for which you have the appropriate rights.

4. **Tonality Consistency:** Maintain a uniform style and tone throughout the article.

5. **Expected Words**:  1500.

---

### PR DESCRIPTION
**Pull request by onyedikachi-david**
Fixes #310
/claim #310
This commit adds a comprehensive guide on GraphQL integration in Vue applications,
covering 5 different approaches for data fetching:

- Apollo Vue
- Villus
- URQL
- Fetch API
- Axios

The guide includes:
- Installation instructions for each library
- Usage examples with Vue 3 Composition API
- Brief explanations of each approach's strengths
- A conclusion summarizing when to use each method

Working repo example: https://github.com/onyedikachi-david/vue-graphql-multiapproach

example link: https://vue-graphql-multiapproach.vercel.app/

### CODE REVIEW

**Comment by onyedikachi-david** [comment]
Please review @amitksingh1490

**Comment by amitksingh1490** [comment]
@onyedikachi-david  Can you move this to blogs similar to what I have done for angular one

**Comment by onyedikachi-david** [comment]
> @onyedikachi-david  Can you move this to blogs similar to what I have done for angular one

Okay

**Comment by onyedikachi-david** [comment]
Done @amitksingh1490

**Comment by amitksingh1490** [comment]
@onyedikachi-david  The content is very similar to the angular lets try to add different analogies. Moving this to Draft

**Comment by amitksingh1490** [comment]
@onyedikachi-david Please take this feedback and update the angular blog accordingly [twitter.com/JoviDeC/status/1815101625280987264](https://twitter.com/JoviDeC/status/1815101625280987264)

**Comment by Frenzyritz13** [comment]
Hey @onyedikachi-david , if you are still working on this, I would recommend using this checklist to review your article: https://docs.google.com/document/d/1Bw9iT4ws9q093kCJsnStfpByJljn-wRPNtc575s3_R8/edit?usp=sharing
And if you want discuss changes and flow of it feel free to put some time on my calendar here: https://calendly.com/ritvi

**Comment by shegz101** [comment]
> Hey @shegz101, if you are still working on this, I would recommend using this checklist to review your article: https://docs.google.com/document/d/1Bw9iT4ws9q093kCJsnStfpByJljn-wRPNtc575s3_R8/edit?usp=sharing And if you want discuss changes and flow of it feel free to put some time on my calendar here: https://calendly.com/ritvi

Hello @Frenzyritz13, I already dropped this. Thank you!
Someone is presently working on this.

**Comment by onyedikachi-david** [comment]
Thank you @Frenzyritz13, Yes I am on it. Almost done.

**Comment by Frenzyritz13** [comment]
Hey @onyedikachi-david any updates on the article? We would love to publish it today if you are done.

**Comment by onyedikachi-david** [comment]
Yes there's. I'll make a push in 3hrs

**Comment by Frenzyritz13** [comment]
Hey @onyedikachi-david just wondering if you pushed the changes. Did you get a chance to do it?

**Comment by onyedikachi-david** [comment]
Hello, @Frenzyritz13, Just pushed.

**Review by amitksingh1490 — APPROVED** [review]

**Pull request merged**
