### PR TITLE
detailed guide for telemetry

### LINKED ISSUE #140: Write a detailed guide for telemetry
Telemetry is a recent feature that was integrated and documented here: 
https://tailcall.run/docs/operators/telemetry/

Write a detailed guide using the telemetry feature about how one can use it.

- Add screenshots where necessary
- Add forward/backward links to the Apollo Guide

### PR DESCRIPTION
**Pull request by Bhavyajain21**
Raising a draft PR for this

/fixes #140 
/claim #140

### CODE REVIEW

**Comment by Bhavyajain21** [comment]
Hey @tusharmath, can you review the PR so far?
Will add more about the integrations soon.

**Comment by tusharmath** [comment]
please add `fixes #140` with the PR description, so that the issue can close automatically on PR merged.

**Comment by Bhavyajain21** [comment]
> please add `fixes #140` with the PR description, so that the issue can close automatically on PR merged.

Done

**Comment by Bhavyajain21** [comment]
Will open again after updating

**Pull request closed without merging**
