### PR TITLE
feat: Tailcall Config Generator Form

### PR DESCRIPTION
**Pull request by mehulmathur001**
@tusharmath, Me and @Bhavyajain21 have collaborated on this issue and would love your feedback on the form. Your input is essential for refining the layout and improving the user experience. Please review the changes and share your thoughts. Your feedback will help us ensure the best possible outcome.

/claim #373

### CODE REVIEW

**Comment by hunxjunedo** [comment]
great work there @mehulmathur001 @Bhavyajain21, I had been working on this and was able to make the form very similar to yours using the same npm package, however I couldn't raise a PR as I had a few more things to do after setting up `rjfs`, which I see missing here as well:
- options have a pretty bad UI by default, they show up as `Option 1` and `Option 2` which confuses the visitor, rather they should be like `setup cache config. ` / `leave cache config` or `stdout` / `otlp` etc.
- the current version doesn't export to GraphQL format as required.
- glad that you guys noticed that long descriptions are making mess, however the code is commented out idk why
- ajv is being used as a validator, which as far as I remember doesn't support formats like `int64` `uin32` etc.
- the theme looks a bit off compared to the theme of the website, colors and margins need to be adjusted.
- the form isn't properly integrated with the playground, it doesn't even appear unless the visitor scrolls down, this can be improved.
- the UI for mobile has to be fine-tuned, it doesn't look alright as required (the info icon is added by me for testing): 
image
image




it would be great if we could collaborate on this, and work towards a common goal, will be great experience working together.

**Comment by mehulmathur16** [comment]
@hunxjunedo We have just raised a base PR currently and for moving forward we will require inputs from @tusharmath.

Regarding the points you mentioned above, we also have tried out a few things like using tooltips by modifying templates. But after doing that we observed there's an inconsistency between the fields rendered, as rjsf treats each and every type of field differently. Hence removed tooltips part. Also, if we try to make it consistent by overriding everything then we'll be losing rjsf native form styles which look pretty decent to us.

This is just a base PR and we're aware of the points you've raised. We wanted to raise a PR on the work we have done till now for progress. We have experimented a lot of things on this for making it better and we're still trying to figure out how can this be made more better, so don't take this up as the final UI 😄

**Comment by Bhavyajain21** [comment]
https://github.com/user-attachments/assets/8d06d334-7e6f-45d6-8e9f-1d0174a97080

@tusharmath , this is the progress so far that we have made. We would appreciate your inputs on the same, please let us know and we can take it forward.

**Comment by tusharmath** [comment]
Make it work correctly. Have a good user experience, don't worry about the looks as much.

**Comment by tusharmath** [comment]
@mehulmathur001 @Bhavyajain21 first of all congratulations on the collaboration. This is perhaps the first large collaboration I am seeing on Tailcall, so kudos to that!

I think we are getting somewhere with this. The UI however looks very "auto-generated" and not inline with the design of the website. Here are a few suggestions to make it better

- Deploy the generator UI on a different URL `/app/config` instead of the playground (for now)
- The UI contains a lot of boxes and borders and nesting. You could use some collapsable sections to configure different part of the configuration.
- You could add a side nav to quickly reach different parts of the configuration
- Don't read the JSON schema for everything, because that will create a very ugly UI.

**Comment by tusharmath** [comment]
Moving to draft to reduce noise and improve CI efficiency. Once you are ready just mark it as "ready to review". Feel free to give a shoutout on the #contributors channel on Discord if you want immediate attention.

**Comment by mehulmathur16** [comment]
@tusharmath Thanks for the review. We'll make the above changes.

**Comment by tusharmath** [comment]
I have been looking at this project — https://www.youtube.com/watch?v=qV8Cho93oxU

Check it out and see if we can leverage it in someway. The UI looks good.

**Comment by mehulmathur16** [comment]
Sure @tusharmath

**Comment by Bhavyajain21** [comment]
https://github.com/user-attachments/assets/f869fd34-d9ac-4b31-af44-bb2a52cc3d67

**Comment by Bhavyajain21** [comment]
@tusharmath, we have updated the form with the collapsible fields. Please have a look.

**Comment by tusharmath** [comment]
Closing this PR for now. The UX needs a lot of work. Moving to draft. I will be posting the designs for this page via figma in a few days.

**Comment by tusharmath** [comment]
/tip $100 

For the attempt!

**Pull request closed without merging**
