### PR TITLE
Understanding GraphQL Subscriptions

### PR DESCRIPTION
**Pull request by ayush2390**
Created a detailed outline for the blog **Understanding GraphQL Subscriptions**. In the outline I have covered everything about the GraphQL Subscriptions like intro to GraphQL Subscriptions, benefits of GraphQL Subscriptions, best practices, how to use it, etc

### CODE REVIEW

**Comment by amitksingh1490** [comment]
Brief Description
Write a brief description (2-3 sentences) of what the blog post will cover and what the reader will learn from it.
This is missing. What is the intent of writing this blog?

**Comment by ayush2390** [comment]
In this blog, you will learn how GraphQL Subscriptions work in real-time data updates in applications, the important components involved, and best practices for their implementation. The intent is to offer a thorough understanding of how GraphQL Subscriptions work, their advantages, challenges, and practical applications in modern web development.

**Comment by amitksingh1490** [comment]
Wouldn't we need any diagrams in this blog?

**Comment by ayush2390** [comment]
Yes, we will need diagrams and flow-charts in the blog. Should I also mention the diagrams in the blog outline?

**Pull request closed without merging**
