### PR TITLE
chore: Auto Publish Blogs to Dev.to

### PR DESCRIPTION
**Pull request by ssddOnTop**
/claim https://github.com/tailcallhq/tailcallhq.github.io/issues/357

### CODE REVIEW

**Comment by hunxjunedo** [comment]
There seems to be some issues with this PR:
- [on this line](https://github.com/tailcallhq/tailcallhq.github.io/blob/e3b7fc7c47bb4bb1f4a39e9c2abf14285b9bb832/publish-hashnode/src/utils/devto.ts#L63) all published articles are fetched, and then linearly searched which is a costly approach especially when on GH Actions.
- [on this line](https://github.com/tailcallhq/tailcallhq.github.io/blob/e3b7fc7c47bb4bb1f4a39e9c2abf14285b9bb832/publish-hashnode/src/utils/devto.ts#L66) the type of `post` argument is `CreateDraftInput` which is incorrect for the `dev.to` API's expected input: [api docs](https://developers.forem.com/api/v1#tag/articles/operation/createArticle)
- the way the articles are published and updated is possibly wrong, as `Tailcall` will be registered as an organization instead of an individual user
- there is no support for publishing in parallel as it was required, instead it waits for Hashnode to complete before publishing to `dev.co`, and if an error is occurred in one, it automatically fails the other

@tusharmath I have a plan in mind, which works in parallel, will need to discuss a few things before finalizing and raising the PR.

**Comment by ssddOnTop** [comment]
> There seems to be some issues with this PR:
> 
> * [on this line](https://github.com/tailcallhq/tailcallhq.github.io/blob/e3b7fc7c47bb4bb1f4a39e9c2abf14285b9bb832/publish-hashnode/src/utils/devto.ts#L63) all published articles are fetched, and then linearly searched which is a costly approach especially when on GH Actions.
> * [on this line](https://github.com/tailcallhq/tailcallhq.github.io/blob/e3b7fc7c47bb4bb1f4a39e9c2abf14285b9bb832/publish-hashnode/src/utils/devto.ts#L66) the type of `post` argument is `CreateDraftInput` which is incorrect for the `dev.to` API's expected input: [api docs](https://developers.forem.com/api/v1#tag/articles/operation/createArticle)
> * the way the articles are published and updated is possibly wrong, as `Tailcall` will be registered as an organization instead of an individual user
> * there is no support for publishing in parallel as it was required, instead it waits for Hashnode to complete before publishing to `dev.co`, and if an error is occurred in one, it automatically fails the other

For the last one I already planned to move it to seperate workspace.

For searching the article.. I don’t think linear search will be a major issue here.. this is not a hot code.

Thanks for the review, I’ll fix them soon.

**Comment by bnchi** [comment]
> For searching the article.. I don’t think linear search will be a major issue here.. this is not a hot code.

I highly doubt this will be an issue, searching through a list of 100/200 whatever posts is pretty trivial . What you want to be aware of is pagination. 

https://developers.forem.com/api/v0#tag/articles/operation/getUserArticles

**Comment by ssddOnTop** [comment]
there are some issues with this PR..

I am open for collabs on this issue.

**Comment by amitksingh1490** [comment]
Closing in favour of https://github.com/tailcallhq/tailcallhq.github.io/pull/363

**Pull request closed without merging**
