### PR TITLE
feat: Add CodeSandBox

### LINKED ISSUE #20: Add a sandbox for Tailcall on the Home Page to play around with the server
Insert a sandbox like one on [trpc.io] on the tailcall home page.

**Features**
- Use `tc init` to bootstrap the project. 
- Make sure there is a `.tailcallrc.graphql` and intellisense works on the IDE.
- Codespace should start with a running server pointing to a [config.graphql](https://github.com/tailcallhq/tailcall/blob/main/examples/jsonplaceholder.graphql)
- A `graphiql` window should be open on the right to play around with the tailcall server.
- Changes in the file, should restart the server.
- The sandboxed env should load quickly.

[trpc.io]:https://trpc.io

NOTE: Minor UI fixes might be given to make sure the site looks neat.

### PR DESCRIPTION
**Pull request by neo773**
Adds CodeSandBox demo playground. sandbox uses `entr`

https://github.com/tailcallhq/tailcallhq.github.io/assets/62795688/328cb07b-b4d5-4246-a300-fa475d511a3a

/claim #20 

fixes #20

### CODE REVIEW

**Comment by tusharmath** [comment]
@neo773 Thanks for this PR. Can we do a few changes please?

- [ ] Change the "Github Star" button to "Learn More" and point it to the "Get Started" button.
- [ ] Change the "Get Started" button to "Try it out" and point it to the code-spaces link.
- [ ] Move the github button to the top nav, close to "Discord" button.
- [ ] Move the code-spaces repository into the tailcall org.

I think that's a much better developer experience. Opening Codespaces in a separate window makes it easier to work with.

Thanks once again 🙏🙏🙏

**Comment by tusharmath** [comment]
@neo773 Can you transfer ownership of your repository to @tailcallhq

**Comment by tusharmath** [comment]
@neo773 I think this is ready to be merged. IF you could transfer ownership of the repo to tailcallhq and update the code-spaces links, we could have this PR merged.

**Comment by neo773** [comment]
@tusharmath 


A2C2E42A-1170-4D6B-BEA2-CB94A640C0E5

**Review by tusharmath — APPROVED** [review]

**Pull request merged**
