### PR TITLE
feat: CSS equivalent of grid-dark image

### LINKED ISSUE #418: Drop `grid-dark.png`
Drop `grid-dark.png` and use CSS to produce the same effect. It is used in the footer images.

### PR DESCRIPTION
**Pull request by 35C4n0r**
Closes https://github.com/tailcallhq/tailcallhq.github.io/issues/418
/claim https://github.com/tailcallhq/tailcallhq.github.io/issues/418

### CODE REVIEW

**Comment by 35C4n0r** [comment]
@tusharmath PR ready for review
image

image

**Comment by 35C4n0r** [comment]
Currently the `format:fix` and `format:check` commands dosen't format the CSS files, lemme know if I should add that in this PR too.

**Comment by amitksingh1490** [comment]
I've noticed a few differences between the two implementations:

1. **Grid Size**: The grid size in the CSS version appears slightly different compared to the background image version.

2. **Dot Visibility**: The intersections of the horizontal and vertical lines in the CSS version have noticeable thick dots, which are not present in the image version.

3. **Line Visibility**: The lines in the CSS version are less visible compared to those in the image version.


**Here is side by side comparison**
Left has CSS
Right has bg image
image

**Comment by 35C4n0r** [comment]
> I've noticed a few differences between the two implementations:
> 
> 1. **Grid Size**: The grid size in the CSS version appears slightly different compared to the background image version.
> 2. **Dot Visibility**: The intersections of the horizontal and vertical lines in the CSS version have noticeable thick dots, which are not present in the image version.
> 3. **Line Visibility**: The lines in the CSS version are less visible compared to those in the image version.
> 
> **Here is side by side comparison** Left has CSS Right has bg image image

@amitksingh1490 I've tried to bring them as close as possible

**Comment by 35C4n0r** [comment]
image

**Review by amitksingh1490 — APPROVED** [review]

**Pull request merged**
