### PR TITLE
fix(445): Layout of benefits section

### LINKED ISSUE #445: fix layout of the benefits section.
Issue: The title horizontal alignment doesn't match the content below it.

**Comparison**
Screenshot 2024-08-15 at 5 47 05 PM

**Technical Requirements**
- Ensure the layouts work in all screen sizes.

### PR DESCRIPTION
**Pull request by 35C4n0r**
/claim #445
Closes #445

### CODE REVIEW

**Comment by 35C4n0r** [comment]
@tusharmath PR is ready for review

**Comment by 35C4n0r** [comment]
@tusharmath live deployment link: https://3000-35c4n0r-tailcallhqgithu-pi1azve3ba9.ws-us115.gitpod.io/

**Comment by 35C4n0r** [comment]
I've also fixed this logo inconsistency 
image

**Comment by tusharmath** [comment]
closing in favour of https://github.com/tailcallhq/tailcallhq.github.io/pull/454

**Pull request closed without merging**
