### PR TITLE
Understanding GraphQL Subscriptions

### PR DESCRIPTION
**Pull request by ayush2390**
In this blog, you will learn how GraphQL Subscriptions facilitate work in real-time data updates in applications, the important components involved, and best practices for their implementation. The intent is to offer a thorough understanding of how GraphQL Subscriptions work, their advantages, challenges, and practical applications in modern web development.

### CODE REVIEW

**Comment by amitksingh1490** [comment]
run prettier please

**Comment by ayush2390** [comment]
> run prettier please

I have run the prettier

**Review by amitksingh1490 — APPROVED** [review]

**Pull request merged**
