### PR TITLE
fix: fix layout width

### LINKED ISSUE #118: CSS Fix: code shifting on the home page
On the home page when you switch between the "get started" code snippets, the width of the columns change, which is unexpected. This should be a simple CSS fix.

**Technical Requirements**
- No JS, use only CSS to make the fix.
- Ensure CI passes.
- Ensure the fix is responsive and works on all screens sizes.

Screenshot 2024-02-28 at 9 06 12 PM

Screenshot 2024-02-28 at 9 06 22 PM

Screenshot 2024-02-28 at 9 06 30 PM

### PR DESCRIPTION
**Pull request by 35C4n0r**
Closes #118
/claim #118 
Also too care of the breakpoints for Mobie, Ipad and Laptop Screens

### CODE REVIEW

**Comment by 35C4n0r** [comment]
@tusharmath PR is ready for review

**Comment by 35C4n0r** [comment]
If you have any additional suggestions, please let me know, I'll add it in this PR

**Comment by tusharmath** [comment]
Horizontal Scroll
Screenshot 2024-03-02 at 10 56 41 AM

**Comment by 35C4n0r** [comment]
Thanks for the review, fixing it asap.

**Comment by 35C4n0r** [comment]
@tusharmath fixed the scrolling issue, ready for review.

**Comment by tusharmath** [comment]
Still happening on a different screen size.

Screenshot 2024-03-02 at 11 56 49 AM

**Comment by 35C4n0r** [comment]
😕 It looks fine on my side
image

**Comment by tusharmath** [comment]
Check the space after the hamburger menu on the top right. There shouldn't be any space.

**Comment by 35C4n0r** [comment]
I have removed the scaling @tusharmath, and I think that fixes it. Kindly check on your side once.

**Comment by 35C4n0r** [comment]
> Check the space after the hamburger menu on the top right. There shouldn't be any space.

IMHO it's not the navbar, it was this image

Without scaling
image
image


With scaling (overflows)
image

**Review by tusharmath — APPROVED** [review]

**Comment by tusharmath** [comment]
Looks great! Thanks 
/tip 30$

**Comment by 35C4n0r** [comment]
> Looks great! Thanks /tip 30$

😊 @tusharmath Thanks a lot.

**Pull request merged**
