### PR TITLE
docs: Add comprehensive GraphQL in Angular guide with 5 approaches

### LINKED ISSUE #311: Write a Guide for Using GraphQL with Angular
**Write a Guide for Using GraphQL with Angular, similar to the one created for React (see [React Guide](https://tailcall.run/graphql/graphql-react-client/)).**

**Objective:** Outline the top five approaches for integrating GraphQL with Angular.

---
### Approach 1
1. Installation and Integration Steps
2. Code Snippets

... Four more approaches

## Detailed Comparison Table

Create a detailed comparison table of all five methods, including factors like:

1. Bundle Size
2. Learning Curve
3. Caching Capabilities
4. Community Support
5. Additional Features

## Error Handling

Expand on error handling strategies for each method, providing detailed examples of how to gracefully handle and display errors.

## Conclusion

---

# **Requirements for Submission:**

1. **Code Verification:** Ensure all code snippets included in the article are linked to a working GitHub repository. Utilize the Tailcall backend with GraphQL on top of [jsonplaceholderAPI](https://jsonplaceholder.typicode.com/) for examples in the article. There should be a repository containing the Tailcall GraphQL configuration and a README to start the server so readers can try it.

2. **Performance Claims:** Substantiate any performance-related statements with benchmark data. Include relevant links or appendices showcasing these benchmarks to maintain credibility.

3. **Image Usage:** Use only images that are free from copyright restrictions or for which you have the appropriate rights.

4. **Tonality Consistency:** Maintain a uniform style and tone throughout the article.

5. **Expected Words**:  1500.

---

### PR DESCRIPTION
**Pull request by onyedikachi-david**
Fixes #311
/claim #311

- Cover Apollo Angular, Urql, GraphQL-Request, Axios, and Fetch API
- Include detailed comparison table of approaches
- Add sections on common issues and resolutions
- Provide conclusion with recommendations for different use cases"

Working angular repo: https://github.com/onyedikachi-david/angular-graphql-multiapproach

### CODE REVIEW

**Comment by onyedikachi-david** [comment]
@amitksingh1490 Could you please take a look at my PR when you get a chance? Thank you.

**Comment by amitksingh1490** [comment]
@Frenzyritz13 this also needs a review please have a look once you have time

**Comment by amitksingh1490** [comment]
getting warning on your demo app
```
NG02801: Angular detected that `HttpClient` is not configured to use `fetch` APIs. It's strongly recommended to enable `fetch` for applications that use Server-Side Rendering for better performance and compatibility. To enable `fetch`, add the `withFetch()` to the `provideHttpClient()` call at the root of the application.
```

**Comment by onyedikachi-david** [comment]
> getting warning on your demo app
> 
> ```
> NG02801: Angular detected that `HttpClient` is not configured to use `fetch` APIs. It's strongly recommended to enable `fetch` for applications that use Server-Side Rendering for better performance and compatibility. To enable `fetch`, add the `withFetch()` to the `provideHttpClient()` call at the root of the application.
> ```

I ignored it since it was working, just fixed it now, you may pull latest commit.

**Review by amitksingh1490 — APPROVED** [review]

**Comment by amitksingh1490** [comment]
@onyedikachi-david Please take this feedback and update accordingly https://twitter.com/JoviDeC/status/1815101625280987264

**Pull request merged**
