### PR TITLE
fix: fix Search focus

### LINKED ISSUE #167: fix the search box
Clicking on the search box sometimes loses the focus of the cursor. Sometimes even `Cmd + K` doesn't focus the cursor on the text box. Fix it!

Go here an click on the search box.
https://tailcall.run/docs/

### PR DESCRIPTION
**Pull request by jkcs**
/claim #167
close #167

### CODE REVIEW

**Comment by tusharmath** [comment]
@jkcs It still isn't working for me. Can you share a recording? Did u try throttling your network?

**Comment by jkcs** [comment]
Are you using the development environment opened with `npm run build && npm run serve`?

**Comment by jkcs** [comment]
https://github.com/tailcallhq/tailcallhq.github.io/assets/38372737/32d17caa-b4b8-4518-89ed-68ec80812339

**Comment by jkcs** [comment]
I'm not sure if you're using the `build` command. If you start with `start` or `docusaurus` CMD, the search source JSON file will not be generated, and the input box will remain in a "loading" state.

**Comment by tusharmath** [comment]
Uploading Screen Recording 2024-05-11 at 12.54.16 PM (1).mov…

**Comment by jkcs** [comment]
@tusharmath Can't see the video you sent. Could you please try sending it again?

**Comment by tusharmath** [comment]
https://github.com/tailcallhq/tailcallhq.github.io/assets/194482/185d9769-7fff-4b5b-8248-a9bf78114c1f

**Comment by jkcs** [comment]
@tusharmath Thank you for providing the video. According to my research, this is a Safari-specific issue where calling focus outside of the click event and within asynchronous callbacks will not work. I have found the best solution and fixed this problem. You can give it another try.

**Comment by tusharmath** [comment]
Im on chrome.

**Comment by tusharmath** [comment]
closing in favour of https://github.com/tailcallhq/tailcallhq.github.io/pull/247

**Pull request closed without merging**
