### PR TITLE
feat: Merge N+1

### LINKED ISSUE #256: merge n+1 pages
Merge all the N + 1 pages into one and move it under guide.

### PR DESCRIPTION
**Pull request by Bhavyajain21**
/claim #256 
/fixes #256

### CODE REVIEW

**Comment by Bhavyajain21** [comment]
@tusharmath need to know about the path names referred here in the file -> /docs/getting_started/introduction.md

**Comment by Bhavyajain21** [comment]
@tusharmath please review

**Review by tusharmath — CHANGES_REQUESTED** [review]
keep the canvas file.

**Comment by Bhavyajain21** [comment]
> keep the canvas file.

Added! @tusharmath

**Comment by tusharmath** [comment]
This was a duplicate PR

https://tailcall.run/developers/bounty/#the-rules-of-the-game

**Pull request closed without merging**
