### PR TITLE
fix search bar modal focus

### LINKED ISSUE #167: fix the search box
Clicking on the search box sometimes loses the focus of the cursor. Sometimes even `Cmd + K` doesn't focus the cursor on the text box. Fix it!

Go here an click on the search box.
https://tailcall.run/docs/

### PR DESCRIPTION
**Pull request by hrshkshri**
/claim #167 
fixes #167 

This PR fixes the issue with the search bar modal not focusing on Desktop/mobile.

Feel free to check and give feedback.

### Desktop changes

https://github.com/tailcallhq/tailcallhq.github.io/assets/108923011/2947b4c8-81fd-4a03-a693-78afe1cb7ff6

### Mobile changes

https://github.com/tailcallhq/tailcallhq.github.io/assets/108923011/149e40bf-87c2-4b7a-92bb-089994f5c295

Thanks

### CODE REVIEW

**Comment by hrshkshri** [comment]
Hey @tusharmath  PTAL at the solution for #167.

**Comment by tusharmath** [comment]
can you upload a recording with devtools enabled and with throttling.

**Comment by hrshkshri** [comment]
> can you upload a recording with devtools enabled and with throttling.

Hey @tusharmath 
Sorry for the late response (Was busy with my exams)

Sure thing

Here is the video


https://github.com/tailcallhq/tailcallhq.github.io/assets/108923011/0442726a-1869-485c-a152-1eb8307d88e4

**Comment by hrshkshri** [comment]
@tusharmath, Let me know if i need to do anything else 
Thanks : )

**Comment by hrshkshri** [comment]
A friendly ping @tusharmath 
Thanks

**Comment by hrshkshri** [comment]
@tusharmath Seeking for review here

**Comment by tusharmath** [comment]
Tried this PR, and it worked on a throttled network.

**Review by tusharmath — APPROVED** [review]

**Pull request merged**
