### PR TITLE
feat: Merge all directive pages into one and move it to guide

### LINKED ISSUE #255: Merge all directive pages into one and move it to guide
Each directive has its own page, which seems unnecessary. We should merge them together into one page and move that into guides.

### PR DESCRIPTION
**Pull request by ezhil56x**
Closes #255
/claim #255 

https://github.com/tailcallhq/tailcallhq.github.io/assets/103899034/f2974ba5-aeff-4642-b46b-e61c411b40ea

### CODE REVIEW

**Comment by tusharmath** [comment]
@ezhil56x build is failing.

**Comment by ezhil56x** [comment]
> @ezhil56x build is failing.

On it!

**Review by tusharmath — CHANGES_REQUESTED** [review]
build failure and conflicts.

**Comment by ezhil56x** [comment]
Will open a new PR in few minutes

**Pull request closed without merging**
