### PR TITLE
chore: change code theme

### PR DESCRIPTION
**Pull request by neo773**
/claim #365

https://github.com/user-attachments/assets/2e92db78-cded-430b-bc1e-5126cd21b097

### CODE REVIEW

**Comment by bnchi** [comment]
You were faster than me in opening the PR I don't think it will be worth it to open another one for this small issues, you might want to check this comment https://github.com/tailcallhq/tailcallhq.github.io/issues/365#issuecomment-2236078591 

Because tailcall docs got a highlighted lines in some of the sections : https://tailcall.run/docs/tailcall-dsl-graphql-custom-directives/#call-directive

With your PR I'm getting these colors now: 

Screenshot 2024-07-18 at 13-16-31 GraphQL Configuration Tailcall

Just gotta remove/change that overridden property

**Comment by neo773** [comment]
@bnchi 

image

Fixed, thanks.

Seems you were going with custom renderer with `react-prism` I did that in my Next.js PR but was easier to just pass the theme config since `<CodeBlock/>`'s built-in.

https://github.com/neo773/tailcallhq.github.io/blob/nextjs-new/marketing/src/components/home/CodeBlock/index.tsx#L7-L97

**Comment by neo773** [comment]
Added copy button and text, uses the the exact same icon from reference.


https://github.com/user-attachments/assets/901856a6-40cf-4345-ae94-19b31463329b

**Comment by tusharmath** [comment]
Snippets with titles don't look right. Titles should be moved into the toolbar.

Screenshot 2024-07-19 at 11 27 03 AM

**Comment by tusharmath** [comment]
Moving to draft to reduce noise and improve CI efficiency. Once you are ready just mark it as "ready to review". Feel free to give a shoutout on the #contributors channel on Discord if you want immediate attention.

**Comment by tusharmath** [comment]
@neo773 Also try to match the height of the toolbar and the border radius of the code snippets.

**Review by tusharmath — APPROVED** [review]

**Pull request merged**
