### PR TITLE
Update playground screenshots

### LINKED ISSUE #225: doc: migration from the internal Playground to the hosted Playground
## Description

Following our migration from the internal Playground to the Tailcall hosted Playground, many of our guides (such as the authentication guide) contain outdated screenshots and images. These need to be updated to reflect the new interface and features as per our hosted solution.

## Relevant Links
- Migration Details: [Issue #1790](https://github.com/tailcallhq/tailcall/issues/1790)
- Initial Documentation Update PR: [PR #224](https://github.com/tailcallhq/tailcallhq.github.io/pull/224)

## Tasks
- [ ] Review all guides and identify all the images that need updating.
- [ ] Capture new screenshots from the Tailcall hosted Playground that match the steps and descriptions in each guide.
- [ ] Update the images in the documentation.

### PR DESCRIPTION
**Pull request by syedbarimanjan**
Fixes #225 
/claim #225

### CODE REVIEW

**Comment by syedbarimanjan** [comment]
@amitksingh1490 can you take a look at the first screenshot if i should change something or keep going on. Thanks.

**Comment by syedbarimanjan** [comment]
@amitksingh1490 @tusharmath can you take a look.Thanks

**Comment by syedbarimanjan** [comment]
@amitksingh1490 @tusharmath can you take a look. Thanks.

**Comment by amitksingh1490** [comment]
@syedbarimanjan,

We're closing this issue in favor of https://github.com/tailcallhq/tailcallhq.github.io/pull/228, in accordance with our bounty guidelines here: https://tailcall.run/docs/contributors/bounty/.

@neo773  submitted an acceptable PR within 24 hours of the attempt. We appreciate your willingness to contribute to Tailcall and encourage you to keep contributing.

Thank you!

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan,
> 
> We're closing this issue in favor of #228, in accordance with our bounty guidelines here: https://tailcall.run/docs/contributors/bounty/.
> 
> @neo773 submitted an acceptable PR within 24 hours of the attempt. We appreciate your willingness to contribute to Tailcall and encourage you to keep contributing.
> 
> Thank you!

The Rules of the Game
Be Quick or Be… Late: No PR within 24 hours? Then it’s open season for that issue again.
There Can Be One Winner: Multiple folks can try, but it's the top PR that emerges victorious. If there's a tie, the first submission takes the prize.
No Copycats: Be original; be yourself. Avoid merely copying someone else's hard work.
Consider Before You Contribute: If there’s already a PR in progress, perhaps take a moment to review it before submitting your own. 

@amitksingh1490 @tusharmath  if you can take a look at the guidelines properly what it states and his work isnt proper there are still some screenshots left and the current ones are cut out form the bottom.

**Comment by syedbarimanjan** [comment]
> > @syedbarimanjan,
> > We're closing this issue in favor of #228, in accordance with our bounty guidelines here: https://tailcall.run/docs/contributors/bounty/.
> > @neo773 submitted an acceptable PR within 24 hours of the attempt. We appreciate your willingness to contribute to Tailcall and encourage you to keep contributing.
> > Thank you!
> 
> The Rules of the Game Be Quick or Be… Late: No PR within 24 hours? Then it’s open season for that issue again. There Can Be One Winner: Multiple folks can try, but it's the top PR that emerges victorious. If there's a tie, the first submission takes the prize. No Copycats: Be original; be yourself. Avoid merely copying someone else's hard work. Consider Before You Contribute: If there’s already a PR in progress, perhaps take a moment to review it before submitting your own.
> 
> @amitksingh1490 if you can take a look at the guidelines properly what it states and his work isnt proper there are still some screenshots left and the current ones are cut out form the bottom.

both of us attempted at the same time just some seconds in between you can take a look and i raised a pr first and the overall quality of my pr is better if you can judge. @amitksingh1490 @tusharmath

**Comment by amitksingh1490** [comment]
@syedbarimanjan your PR has some updated images which were not supposed to be updated
[static/images/docs/rest.png](https://github.com/tailcallhq/tailcallhq.github.io/pull/227/files#diff-35821aabeab899445d3b3b2e49b11021cd3022c796fee305c8e259c57d3a6b04)
and
static/images/docs/rest-user.png.

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan your PR has some updated images which were not supposed to be updated [static/images/docs/rest.png](https://github.com/tailcallhq/tailcallhq.github.io/pull/227/files#diff-35821aabeab899445d3b3b2e49b11021cd3022c796fee305c8e259c57d3a6b04) and static/images/docs/rest-user.png.

why? they are in the previous playground. and i can remove them yet still i was the first to open the pr and both of us attempted at the same time. @amitksingh1490 @tusharmath you should respect my time to complete this issue.

**Comment by amitksingh1490** [comment]
Because those images was for exposing your graphql api's as rest and in our current playground we don't have capability for rest as of now.
I feel sorry for rejecting your PR, but Neo's PR was more complete. Your contribution was highly appreciated, and the margin between both PRs was quite narrow. Please keep contributing!

Thank you for your understanding.

**Comment by syedbarimanjan** [comment]
> Because those images was for exposing your grpahql api's as rest and in our current playground we don't have capability for rest as of now. I feel sorry for rejecting your PR, but Neo's PR was more complete. Your contribution was highly appreciated, and the margin between both PRs was quite narrow. Please keep contributing!
> 
> Thank you for your understanding.

If you have the issue reserved for someone than just assign it to them so other people dont waste thier time working on it please and i am not happy with your response. Thanks @tusharmath @amitksingh1490 my screenshots are still not cut out from the bottom and I can always remove the unwanted ones.

**Comment by tusharmath** [comment]
Hey @syedbarimanjan thanks for your contribution and time 🙏 


I think the main objective for us has always been to ensure merging high-quality work which is where sometimes, older contributors have an edge. I hope you can let this one go and focus on the rest of the open issues. I am happy to take feedback and improve the process and the experience of our contributors. How about you connect with me on DM and continue this discussion there?

For your contributions /tip 10$ ❤️

**Comment by neo773** [comment]
The whole PR was inaccurate to begin with, the requirement was to update GraphQL screenshots not the REST API.
This also required patching the Playground as appending headers were broken I fixed it in this PR https://github.com/tailcallhq/tailcallhq.github.io/pull/226

**Comment by neo773** [comment]
Also I declared my attempt first one hour before you so you clearly knew it was a WIP

**Pull request closed without merging**
